version: '3.1'

networks:
   elk:
    name: elk_external
    external: true

services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
  
  database:
    platform: linux/x86_64
    container_name: database_marketplace
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: marketplace
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - elk
  
  php:
    container_name: php_marketplace
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/MarketPlace
    depends_on:
      - database
    networks:
      - elk
  
  nginx:
    container_name: nginx_marketplace
    image: nginx:stable-alpine
    ports:
      - '8005:80'
    volumes:
      - ./app:/var/www/MarketPlace
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - elk      
  
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: database
    networks:
      - elk