twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        cart: '@App\Service\CartService'
        notifierGlobal: '@App\Service\NotifierService'

when@test:
    twig:
        strict_variables: true
